# Define datasets and folds as a configuration variable
celltypes: ['Primitive_Streak','Early_Mes_EOi','Early_Mes_EOd','Posterior_Mes','HE_Precursor','HE','Mesenchyme','Allantois_Precursor','Blood_Progenitor','Endothelium','Allantois'] # , "PS_EOd"
folds: ['fold0','fold1','fold2','fold3','fold4'] # ,'fold2','fold3','fold4'

directories:
    base: /rds/project/rds-SDzz0CATGms/users/bt392/09_Eomes_invitro_blood/
    results: /rds/project/rds-SDzz0CATGms/users/bt392/09_Eomes_invitro_blood/results/atac/crested/run1/
    conda: /home/bt392/miniconda3/envs/
    rds: /rds/project/rds-SDzz0CATGms/users/bt392/
    
resources:
    genome: /rds/project/rds-SDzz0CATGms/references/10x/refdata-cellranger-arc-mm10-2020-A-2.0.0/fasta/genome.fa
    chromsizes: /rds/project/rds-SDzz0CATGms/users/bt392/09_Eomes_invitro_blood/results/atac/chrombpnet/mm10.chrom.sizes
    
scripts:
    01_train: 01_train.py
    02_contributions: 02_contributions.py